supabase:
  outputs:
    dev:
      type:  "{{ env_var('DB_NAME') }}"
      host:  "{{ env_var('DB_HOST') }}"
      user: "{{ env_var('DB_USER') }}"
      password: "{{ env_var('DB_PASS') }}"
      port:  "{{ env_var('DB_PORT') }}"
      dbname:  "{{ env_var('DB_NAME') }}"
      schema: public
      threads: 1
  target: dev
