supabase:
  outputs:
    dev:
      type: postgres
      host: aws-0-ap-southeast-2.pooler.supabase.com
      user: "{{ env_var('POSTGRES_USER') }}"
      password: "{{ env_var('SUPABASE_PASS') }}"
      port: 5432
      dbname: postgres
      schema: public
      threads: 1
  target: dev

