name: CI

on:
  # workflow_dispatch:
 schedule:
    - cron: 5 8 * * Sun

env:
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_PORT: ${{ secrets.DB_PORT }}
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASS: ${{ secrets.DB_PASS }}
  DB_NAME: ${{ secrets.DB_NAME }}
  
jobs:
  dbt-build:
    runs-on: ubuntu-22.04
    steps:    
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Check env var
        env:
          MY_VAL: ${{ secrets.DB_HOST }}
        run: |
          import os
          for q in (os.getenv("MY_VAL")):
            print(q)
        shell: python        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install -r requirements.txt
      - name: Install dbt Dependencies
        run: dbt deps
      - name: Check dbt version
        run: dbt --version
      - name: Check dbt connection 
        run: dbt debug
      - name: dbt Build
        run: dbt build
